default_install_hook_types:
  - pre-commit
  - post-checkout

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-yaml
    name: Check YAML files syntax
  - id: trailing-whitespace
    name: Ensure no trailing spaces at the end of lines
  - id: debug-statements
    name: Check for leftover debug statements
  - id: end-of-file-fixer
    name: Ensure that files end with a newline
  - id: check-added-large-files


- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.910
  hooks:
    - id: mypy

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
    - id: check-merge-conflict

- repo: https://github.com/asottile/seed-isort-config
  rev: v2.2.0
  hooks:
    - id: seed-isort-config

- repo: https://github.com/pycqa/flake8
  rev: 6.1.0
  hooks:
    - id: flake8
      args: ['--max-line-length=100', '--extend-ignore=E203,W503']

- repo: https://github.com/psf/black
  rev: 23.7.0
  hooks:
    - id: black
