# Generated by Django 3.1.1 on 2020-09-29 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brewery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='step',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='brewery.step'),
            preserve_default=False,
        ),
    ]
