# Generated by Django 3.1.1 on 2020-09-29 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brewery', '0003_auto_20200929_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='ingredient',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='brewery.ingredientstorage'),
        ),
    ]
