# Generated by Django 3.1.1 on 2020-09-29 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewery', '0007_auto_20200929_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='duration',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
