# Generated by Django 3.1.1 on 2020-09-29 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewery', '0008_step_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
