# Generated by Django 3.1.1 on 2020-10-01 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brewery', '0009_auto_20200929_1031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('comment', models.CharField(max_length=200)),
                ('charge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brewery.charge')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brewery.step')),
            ],
        ),
    ]
