# Generated by Django 3.1.1 on 2020-10-01 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brewery', '0010_protocol'),
    ]

    operations = [
        migrations.RenameField(
            model_name='protocol',
            old_name='end',
            new_name='tend',
        ),
        migrations.RenameField(
            model_name='protocol',
            old_name='start',
            new_name='tstart',
        ),
    ]
