# Generated by Django 3.1.1 on 2020-09-17 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewing', '0002_recipe_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientstorage',
            name='amount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
