# Generated by Django 3.1.1 on 2020-09-17 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewing', '0003_ingredientstorage_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='creation',
            field=models.DateTimeField(),
        ),
    ]
