# Generated by Django 3.1.1 on 2020-09-17 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brewing', '0005_auto_20200917_0949'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingredients',
            new_name='Ingredient',
        ),
    ]
