# Generated by Django 3.1.1 on 2020-09-17 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewing', '0006_auto_20200917_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beerstorage',
            name='id',
        ),
        migrations.AddField(
            model_name='beerstorage',
            name='keg_nr',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
