# Generated by Django 3.1.1 on 2020-09-17 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brewing', '0007_auto_20200917_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beerstorage',
            name='content',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='brewing.charge'),
        ),
        migrations.AlterField(
            model_name='beerstorage',
            name='filling',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='beerstorage',
            name='status',
            field=models.CharField(default='empty', max_length=200),
        ),
    ]
