# Generated by Django 3.1.1 on 2020-09-17 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewing', '0008_auto_20200917_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beerstorage',
            name='filling',
            field=models.DateTimeField(blank=True),
        ),
    ]
