# Generated by Django 3.1.1 on 2020-09-17 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brewing', '0009_auto_20200917_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beerstorage',
            name='content',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='brewing.charge'),
        ),
        migrations.AlterField(
            model_name='beerstorage',
            name='keg_nr',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
