# Generated by Django 3.1.1 on 2020-09-17 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brewing', '0010_auto_20200917_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beerstorage',
            name='content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='brewing.charge'),
        ),
    ]
