# Generated by Django 3.1.1 on 2020-09-17 10:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('brewing', '0013_auto_20200917_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
